import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Providers from "../components/Providers";
import ThemeButton from "../components/ThemeButton";
import { cn } from "../utils/cn";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={cn(inter.className, "h-screen bg-white dark:bg-[#121212]")}
      >
        <Providers>
          <header className="py-6">
            <nav className="flex w-full items-center justify-end">
              <ThemeButton styles="mx-4" />
            </nav>
          </header>
          {children}
        </Providers>
      </body>
    </html>
  );
}
